/**
 * Chat Evaluation
 * API de Chat Evaluation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ChatEvaluationFilter {
  to?: string;
  from?: string;
  codeInvolved?: number;
  codeAlert?: number;
}
