import { Attachment } from './../services/model/attachment';
/**
 * EMAIL API
 * API de Email
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EmailRequest {
    applicationCode?: string;
    cc?: Array<any>;
    from?: string;
    message?: string;
    subject?: string;
    to?: Array<any>;
    imagens?: Array<any>;
    attachments?: Array<Attachment>;
}
