/**
 * ALERTA API
 * SMS - Módulo Alertas de SMS que tem como objetivo comunicar aos interessados deliberações das
 * Agências Reguladoras e eventos de segurança relevantes para que as medidas necessárias sejam tomadas
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusApplication } from './statusApplication';


export interface ActionPlanProjection {
    causaRaiz?: string;
    company?: string;
    comprehensiveness?: boolean;
    createdBy?: string;
    creationDate?: string;
    description?: string;
    endDate?: string;
    id?: number;
    idAlerta?: number;
    idInvolved?: number;
    registeredDateInvolved?: string;
    status?: ActionPlanProjection.StatusEnum;
    statusInvolved?: StatusApplication;
    userKeyInvolved?: string;
    viewed?: boolean;
}
export namespace ActionPlanProjection {
    export type StatusEnum = 'CREATED' | 'SHIPPED' | 'EMBRACING' | 'NOT_EMBRACING' | 'IN_ACTION_PLAN' | 'DISAPPROVED' | 'APPROVED' | 'COMPLETED';
    export const StatusEnum = {
        CREATED: 'CREATED' as StatusEnum,
        SHIPPED: 'SHIPPED' as StatusEnum,
        EMBRACING: 'EMBRACING' as StatusEnum,
        NOTEMBRACING: 'NOT_EMBRACING' as StatusEnum,
        INACTIONPLAN: 'IN_ACTION_PLAN' as StatusEnum,
        DISAPPROVED: 'DISAPPROVED' as StatusEnum,
        APPROVED: 'APPROVED' as StatusEnum,
        COMPLETED: 'COMPLETED' as StatusEnum
    }
}
