import { BaseEntity } from './../../model/base-entity.model';
/**
 * ALERTA API
 * SMS - Módulo Alertas de SMS que tem como objetivo comunicar aos interessados deliberações das
 * Agências Reguladoras e eventos de segurança relevantes para que as medidas necessárias sejam tomadas
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Alert } from './alert';


export class Attachment implements BaseEntity {
  constructor(
    public id?: any,
    public name?: string,
    public size?: number,
    public type?: string,
    public file?: string|any,
    public uploadDate?: Date,
    public description?: string,
    public userUpload?: string,
    public status?: boolean,
    public alert?: Alert,
  ) {}
}
