/**
 * ALERTA API
 * SMS - Módulo Alertas de SMS que tem como objetivo comunicar aos interessados deliberações das
 * Agências Reguladoras e eventos de segurança relevantes para que as medidas necessárias sejam tomadas
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StatusApplication } from './statusApplication';


export interface EvaluationComprehensivenessProjection {
    appraiser?: string;
    codigoAlert?: string;
    company?: string;
    comprehensiveness?: boolean;
    dateEvaluation?: Date;
    descriptionAlert?: string;
    id?: number;
    idAlert?: number;
    idInvolved?: number;
    idOccurrence?: number;
    justificationForNotApplicable?: string;
    justify?: string;
    rated?: boolean;
    registeredDateInvolved?: string;
    responsedDateInvolved?: string;
    statusInvolved?: StatusApplication;
    titleAlert?: string;
    userKeyInvolved?: string;
}
